#!/bin/bash

_help="\

    data2tsd
    ~~~~~~~~
    Upload your files and directories to TSD - safely, efficiently, simply.

    Usage
    ~~~~~
    data2tsd some-file
    data2tsd some-directory

    If you want to interact with the test API add: '--env test' to
    your comman, e.g.:

    data2tsd some-file --env test

"

if [[ $# -lt 1 ]]; then
    echo ""
    echo "  Missing arguments, exiting"
    echo "  For help type: data2tsd --help"
    echo ""
    exit 1
fi

if [[ $1 == '--help' ]]; then
    printf "%s\n" "$_help"
    exit 0
fi

if [[ -d $1 ]]; then
    tacl --data $1 --pre 'archive,compress' --post 'restore,decompress' $@
    exit 0
else
    tacl --data $1 --pre 'compress' --post 'decompress' $@
    exit 0
fi
