#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Missing arguments, exiting"
    echo "tacl --help for help"
    echo "tacl --guide for a longer explanation"
    exit 1
fi


collect_credentials() {
    read -p 'User > ' USERNAME
    read -s -p 'Password > ' PASSWORD; echo
    read -p 'OTP > ' OTP
}

exec_client() {
    python /lib/python2.7/site-packages/tsdapiclient/client.py \
        --user_name $USERNAME --password $PASSWORD --otp $OTP $@
}

if [[ $1 == '--help' ]]; then
    exec_client $1
    exit 0
elif [[ $1 == '--guide' ]]; then
    exec_client $1
    exit 0
fi

echo $@

# pre-upload processing: options
# ------------------------------
# if type is file (e.g. already a tar or zip)
# exec_client --filename <name> $@
    # and if encrypt
    # gpg -e -r $RECIPIENT $FILE | exec_client $@
# elif type is dir
    # archive
    # tar -cf - $DIR | exec_client $@
        # and if encrypt
        # tar -cf - $DIR | gpg -e -r $RECIPIENT | exec_client $@

# questions:
# encryption optional?
# decryption and untar optional in API?

collect_credentials
exec_client $@
