#!/bin env python

"""API client for data uploads."""

import getpass
import sys
import click

from tsdapiclient.authapi import get_jwt_tsd_auth
from tsdapiclient.config import ENV
from tsdapiclient.configurer import read_config
from tsdapiclient.fileapi import streamfile, streamstdin
from tsdapiclient.tools import _check_present


def print_data_guide():
    guide_text = """\

        TSD API client command-line tool: tacl
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Usage: tacl [OPTIONS]

        Options
        ~~~~~~~

        --env       Either 'test' or 'prod' environment.
        --pnum      Project number.
        --data      Path to file or folder you want to upload.
        --pre       (Optional) Comma-separated string specifying pre-upload data processing:
                        - 'archive': create a tarball
                        - 'compress': use gzip compression
                        - 'encrypt': encrypt data using AES
        --post      (Optional) Comma-separated string specifying post-upload data processing (server-side):
                        - 'restore': restore the tarball to a directory
                        - 'decompress': decompress data
                        - 'decrypt': decrypt data
        -recipient  (Optional) GPG recipient - only when using 'encrypt' or 'decrypt' in pre and/or post
                    expression.

        Importing data to TSD
        ~~~~~~~~~~~~~~~~~~~~~
        tacl --env <test,prod> --pnum p11 --data <filename, dirname> --pre 'archive,compress,encrypt' --post 'restore,decompress,decrypt' --recipient <gpg-recipient>

        API docs
        ~~~~~~~~
        test.api.tsd.usit.no/v1/docs/tsd-api-integration.html

    """
    print guide_text

def parse_post_processing_expression(expr, encryptedpw):
    """
    Map expressions to custom headers.

    Params
    ------
    expr: str
        e.g. 'restore,decompress,decrypt'
    encryptedpw: str
        base64 encoded, gpg encrypted, AES secrek key

    Returns
    -------
    dict

    """
    if expr == 'none':
        return {'Content-Type': 'application/octet-stream'}
    elif expr == 'decrypt':
        return {'Content-Type': 'application/aes',
                'Aes-Key': encryptedpw}
    elif expr == 'decompress':
        return {'Content-Type': 'application/gz'}
    elif 'decompress' in expr and 'decrypt' in expr:
        return {'Content-Type': 'application/gz.aes',
                'Aes-Key': encryptedpw}
    elif expr == 'restore':
        return {'Content-Type': 'application/tar'}
    elif 'restore' in expr and 'decompress' in expr and 'decrypt' in expr:
        return {'Content-Type': 'application/tar.gz.aes',
                'Aes-Key': encryptedpw}
    elif 'restore' in expr and 'decrypt' in expr:
        return {'Content-Type': 'application/tar.aes',
                'Aes-Key': encryptedpw}
    elif 'restore' in expr and 'decompress' in expr:
        return {'Content-Type': 'application/tar.gz'}
    else:
        print 'expression not parseable'
        raise Exception


@click.command()
@click.option('--env', default='test', help='which environment you want to interact with')
@click.option('--pnum', default=None, help='project numbers')
@click.option('--config', default=None, help='path to config file')
@click.option('--guide', is_flag=True, default=False, help='print help text')
@click.option('--data', default=None, help='path to file')
@click.option('--user_name', default=None, help='TSD project user name')
@click.option('--password', default=None, help='TSD password')
@click.option('--otp', default=None, help='one time passcode')
@click.option('--encryptedpw', default=None, help='encrypted password used in symmetric data encryption')
@click.option('--pre', default=None, help='pre processing expression', required=False)
@click.option('--post', default=None, help='post processing expression')
@click.argument('fileinput', type=click.File('rb'), required=False, default=None)
def main(env, pnum, config, guide, data, fileinput, user_name,
         password, otp, encryptedpw, pre, post):
    if guide:
        print_data_guide()
        return
    if env not in ['test', 'prod']:
        print 'unknown env'
        sys.exit(1)
    _check_present(env, 'env')
    _check_present(pnum, 'pnum')
    if data is not None:
        _check_present(data, 'data')
        _check_present(user_name, 'user_name')
        _check_present(password, 'password')
        _check_present(otp, 'otp')
        try:
            custom_headers = parse_post_processing_expression(post, encryptedpw)
        except Exception:
            print 'Cannot proceed - unclear data pipeline specification'
            return
        try:
            api_key = read_config()[env]['api_key']
            token = get_jwt_tsd_auth(env, pnum, api_key, user_name, password, otp, 'import')
        except Exception:
            print 'Authentication failed'
            return
        if token:
            if fileinput is None:
                resp = streamfile(env, pnum, data, token, custom_headers=custom_headers)
                if resp.status_code == 201:
                    print 'Data imported'
                else:
                    print 'Data import failed: ', resp.text
            else:
                resp = streamstdin(env, pnum, fileinput, data, token, custom_headers=custom_headers)
                if resp.status_code == 201:
                    print 'Data imported'
                else:
                    print 'Data import failed: ', resp.text
            return
        else:
            print 'Authentication failed'
            return
    else:
        print 'Didn\'t do anything - missing input?'
        return

if __name__ == '__main__':
    main()
